server:
  port: 8080
spring:
  application:
    name: "ReactorContextLab"
  devtools:
    add-properties: false
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true